version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  gitai: gitai/gitai_orb@volatile

jobs:
  noetic:
    docker:
      - image: gitaiinc/gitai-ci:noetic
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - gitai/install_spinnaker
      - gitai/test:
          cache_prefix: cache-noetic
      - slack/status

workflows:
  tests:
    jobs:
      - noetic:
          context: gitai_ci
